name: mi_entorno
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - pip
  - python=3.10
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - beautifulsoup4
      - bs4
      - certifi
      - charset-normalizer
      - contourpy
      - cycler
      - fonttools
      - idna
      - kiwisolver
      - matplotlib
      - numpy
      - packaging
      - pandas
      - pillow
      - pyparsing
      - python-dateutil
      - pytz
      - requests
      - six
      - soupsieve
      - typing-extensions
      - tzdata
      - urllib3
      - wordcloud
