name: mi_entorno
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - nltk
      - gensim
      - scikit-learn
      - matplotlib
      - rdflib
      - sentence-transformers
      - streamlit
      - rapidfuzz
      - tqdm
      - transformers
      - torch
      - requests
      - pandas
