site_name: "Task 2 - Artificial Inteligence and Open Science in Research Software Engineering"
site_url: "https://javizhangg.github.io/Task2-AIAOSIRSE"
nav:
  - HOME: README.md
  - Licencia: LICENSE
